### ISSUE TITLE
Salvar e recuperar dados da emenda de texto livre do PDF

### ISSUE THREAD

**Issue by fragomeni** [lexml/eta-backend-services#20]
Ver
  - https://github.com/lexml/lexml-eta/issues/639
  - https://github.com/lexml/lexml-eta/issues/640

Formato do XML em
https://docs.google.com/document/d/1We-v-MrIUXvNzWNw9xFchLuy6qhvuMc5nVcV9mXX5LA/edit

**Comment by fragomeni** [comment]
Reprovado no teste:

Lança a exceção

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "anexos" is null
	at br.gov.lexml.eta.etaservices.printing.xml.EmendaXmlMarshaller.geraAnexos(EmendaXmlMarshaller.java:193)
	at br.gov.lexml.eta.etaservices.printing.xml.EmendaXmlMarshaller.toXml(EmendaXmlMarshaller.java:50)
```
